# Configurações de conexão com o Supabase (PostgreSQL na Nuvem)
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.gzgxnprvpemsimqvqwrh
spring.datasource.password=010224Gdjg@h
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate (A mágica que cria as tabelas sozinha)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect