# Configurações de conexão com o Supabase (PostgreSQL na Nuvem)
spring.datasource.url=jdbc:postgresql://db.gzgxnprvpemsimqvqwrh.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=010224Gdjg@h

# Configurações do Hibernate (A mágica que cria as tabelas sozinha)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect